baseURL = "https://viduq.github.io/blog/"
languageCode = "en-us"
title = "vdq blog"
theme = "cactus"
publishdir = "public"

[params]
colortheme = "light"
description = "scripta manent"
mainSection = "posts"
tagsOverview = false

# Main menu which appears below site header.
[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "all posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "about"
url = "/about"
weight = 4
